### PR TITLE
Fix bug in math.ceil by returning integral instead of float (fixes #372)

### LINKED ISSUE #372: Bug with math.ceil returning float
The current implementation of Starlark's `math.ceil` will always return a `starlark.Float` as a result of being wrapped by [`newUnaryBuiltin`](https://github.com/google/starlark-go/blob/master/lib/math/math.go#L70).

Python's `math.ceil`, however, will always return an integral, as can be seen in the [docs](https://docs.python.org/3/library/math.html#math.ceil).

Also, Python's `math.ceil` will return an error when called with non-finite numeric values, i.e. `nan`, `+inf`, and `-inf`:

```bash
>>> math.ceil(float("nan"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: cannot convert float NaN to integer
>>> math.ceil(float("inf"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OverflowError: cannot convert float infinity to integer
>>> math.ceil(float("-inf"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OverflowError: cannot convert float infinity to integer
```

But Starlark's implementation allows for them, as can be seen in the [tests](https://github.com/google/starlark-go/blob/master/starlark/testdata/math.star#L20):

```python
...
assert.eq(math.ceil(inf), inf)
assert.eq(math.ceil(nan), nan)
...
assert.eq(math.ceil(-inf), -inf)
...
```

This bug was first mentioned in #370, as can be seen in [this thread](https://github.com/google/starlark-go/issues/370#issuecomment-828793228).

Possible solution:

Extract `math.ceil` from `newUnaryBuiltin` into its own function, `ceil`, that returns the result as an integral and returns an error when said result is not finite.

### PR DESCRIPTION
**Pull request by Algebra8**
Python's math.ceil function always returns a value's ceiling as an
integral, as can be seen in https://docs.python.org/3/library/math.html#math.ceil.

The previous iteration of Starlark's math.ceil, however, would always return a
float, as a result of being wrapped in newUnaryBuiltin. Since ceil is different
from the other wrapped methods, as described above, separate it in its own function.

It is worth noting that Python's math.ceil will also not accept non-finite values,
such as nan, +inf, -inf and will return custom error messages for nan and infinities.
These are also handled in the new ceil function.

Finally, tests are incorporated in testdata/math.star to reflect the changes
described above.

fixes #372

### CODE REVIEW

**Comment by Algebra8** [comment]
@adonovan 

Hello!

Here is a PR to handle the bug discussed in #370.

I look forward to any feedback.

Thanks!

**Comment by Algebra8** [comment]
It is also worth noting that there seems to be some issue with comparing types, as can be seen in the tests [here](https://github.com/google/starlark-go/pull/373/files#diff-517c4372e0c729c7af57c3b172c205e5651b4b064fb0604a734dfd595f11a8daR27).

Essentially, in Python:

```bash
>>> type(3) == "int"
False
>>> type(3) == int
True
```

But in Starlark, the opposite seems to be true. That is:

```python
assert.eq(type(3), "int")  # ok
assert.eq(type(3), int)    # not ok
```

This probably has something to do with [`type_` returning a `String`](https://github.com/google/starlark-go/blob/master/starlark/library.go#L1132), but I haven't looked to deep into it. If it is a bug I would be happy to have a go at fixing it.

File: lib/math/math.go [hunk 1]
```diff
@@ -162,6 +162,37 @@ func log(thread *starlark.Thread, b *starlark.Builtin, args starlark.Tuple, kwar
...
 
+// ceil wraps the Ceil function as a Starlark built-in that
+// returns the ceiling as an Integral.
+func ceil(
+	thread *starlark.Thread,
+	_ *starlark.Builtin,
+	args starlark.Tuple,
+	kwargs []starlark.Tuple,
+) (starlark.Value, error) {
+	var x floatOrInt
```
Comment (adonovan) [inline lib/math/math.go:173]: It is not correct to use floatOrInt here. If x is an int, we should return it unchanged, not convert it to a float, which may lose information.

File: lib/math/math.go [hunk 2]
```diff
@@ -162,6 +162,37 @@ func log(thread *starlark.Thread, b *starlark.Builtin, args starlark.Tuple, kwar
 	return starlark.Float(math.Log(float64(x)) / math.Log(float64(base))), nil
 }
 
+// ceil wraps the Ceil function as a Starlark built-in that
+// returns the ceiling as an Integral.
+func ceil(
+	thread *starlark.Thread,
```
Comment (adonovan) [inline lib/math/math.go:168]: Put all this on one line: func ceil(...) ... {

File: lib/math/math.go [hunk 3]
```diff
@@ -162,6 +162,37 @@ func log(thread *starlark.Thread, b *starlark.Builtin, args starlark.Tuple, kwar
...
+
+	if err := starlark.UnpackPositionalArgs(
+		"ceil", args, kwargs, 1, &x,
+	); err != nil {
+		return nil, err
+	}
+
+	result := math.Ceil(float64(x))
+
+	// Python's math.ceil raises an error for inf and nan.
```
Comment (adonovan) [inline lib/math/math.go:183]: You don't need this comment: it's obvious from the need to return an int that these inputs are invalid.

Also, combine the checks and errors, and report the supplied value, not the intermediate `result`:
```
if !isInf... || isNan... {
   return nil, fmt.Errorf("ceil: invalid argument %v", x)
}
```
But if you use NumberToInt, you don't need this check.

File: lib/math/math.go [hunk 4]
```diff
@@ -162,6 +162,37 @@ func log(thread *starlark.Thread, b *starlark.Builtin, args starlark.Tuple, kwar
...
+	// This is because it always returns an integral and cannot convert
+	// any of these to an integral.
+	if math.IsInf(result, 0) {
+		return nil, fmt.Errorf("cannot convert float infinity to integer")
+	}
+	if math.IsNaN(result) {
+		return nil, fmt.Errorf("cannot convert float NaN to integer")
+	}
+
+	return starlark.MakeInt64(int64(result)), nil
```
Comment (adonovan) [inline lib/math/math.go:193]: This conversion is lossy for large values. Use starlark.NumberToInt.

File: starlark/testdata/math.star [hunk 5]
```diff
@@ -17,16 +17,24 @@ assert.eq(math.ceil(10.0), 10.0)
...
+assert.eq(type(math.ceil(0.4)), "int")
+assert.eq(type(math.ceil(10)), "int")
+assert.eq(type(math.ceil(-10.0)), "int")
+assert.eq(type(math.ceil(-0.5)), "int")
+assert.fails(
+  lambda: math.ceil(inf), "cannot convert float infinity to integer")
+assert.fails(
+  lambda: math.ceil(-inf), "cannot convert float infinity to integer")
+assert.fails(
+  lambda: math.ceil(nan), "cannot convert float NaN to integer")
```
Comment (adonovan) [inline starlark/testdata/math.star:37]: Let's add a test for a float value larger than int64.

File: lib/math/math.go [hunk 6]
```diff
@@ -67,7 +67,7 @@ import (
 var Module = &starlarkstruct.Module{
 	Name: "math",
 	Members: starlark.StringDict{
-		"ceil":      newUnaryBuiltin("ceil", math.Ceil),
+		"ceil":      starlark.NewBuiltin("ceil", ceil),
 		"copysign":  newBinaryBuiltin("copysign", math.Copysign),
 		"fabs":      newUnaryBuiltin("fabs", math.Abs),
 		"floor":     newUnaryBuiltin("floor", math.Floor),
```
Comment (adonovan) [inline lib/math/math.go:73]: The floor function needs the same treatment.

**Comment by adonovan** [comment]
> It is also worth noting that there seems to be some issue with comparing types

This is required by the spec, it's not a bug. I wouldn't have designed it this way, but it is what it is.

File: lib/math/math.go (hunk 3 above)
Comment (Algebra8) [reply lib/math/math.go:183]: Thanks for pointing that out. `NumberToInt` is a great abstraction and carries the same error messages.

File: lib/math/math.go (hunk 1 above)
Comment (Algebra8) [reply lib/math/math.go:173]: Great point, thanks for pointing that out.

File: starlark/testdata/math.star (hunk 5 above)
Comment (Algebra8) [reply starlark/testdata/math.star:37]: So, if the float value is significantly larger than `math.MaxInt64`, then the function works as expected, e.g.

```python
f = 1.8446744073709552e+19
assert.eq(math.ceil(f), f)  # ok
```

However, if it is slightly larger, then we'll get an overflow:

```python
q = 9223372036854775807.5
print(math.ceil(q))  # -9223372036854775808
```

This seems to be because `q` is close enough to `math.MaxInt64` that the [check in `finiteFloatToInt` will register it as an int](https://github.com/google/starlark-go/blob/master/starlark/int.go#L427).

Is this ok? Or should the `ceil` function take this into consideration?

**Comment by adonovan** [comment]
(I really don't understand the theory of GitHub's PR comments UI. It won't let me respond to your comment directly.)

> This seems to be because q is close enough to math.MaxInt64 that the check in finiteFloatToInt will register it as an int.

You've discovered a beautifully subtle bug which I have filed as https://github.com/google/starlark-go/issues/375 since it affects the interpreter core. I'll send a fix for that presently.

File: starlark/testdata/math.star (hunk 5 above)
Comment (adonovan) [reply starlark/testdata/math.star:38]: See https://github.com/google/starlark-go/pull/376/files

File: starlark/testdata/math.star [hunk 7]
```diff
@@ -17,16 +17,25 @@ assert.eq(math.ceil(10.0), 10.0)
...
 assert.eq(math.ceil(-10.0), -10.0)
 assert.eq(math.ceil(-1), -1.0)
 assert.eq(math.ceil(-10), -10.0)
-assert.eq(math.ceil(-inf), -inf)
+assert.eq(type(math.ceil(0)), "int")
+assert.eq(type(math.ceil(0.4)), "int")
+assert.eq(type(math.ceil(10)), "int")
+assert.eq(type(math.ceil(-10.0)), "int")
+assert.eq(type(math.ceil(-0.5)), "int")
+assert.eq(math.ceil(1.8446744073709552e+19), 1.8446744073709552e+19)
```
Comment (adonovan) [inline starlark/testdata/math.star:32]: It's unclear what the first constant signifies. `float(1<<64)`? The same thing plus or minus one? Derive the argument to make it clear. 

Is the second argument intentionally a float? It may compare equal to the int returned by ceil, but it would be better to use an expression that is actually an int.

**Review by adonovan — COMMENTED** [review]
Production code looks good. One last question about the tests! Thanks for your patience.

**Comment by Algebra8** [comment]
@adonovan 

> Production code looks good. One last question about the tests! Thanks for your patience.

No, thank you for your patience and feedback! I really appreciate the time you've taken for it 🙏 

> It's unclear what the first constant signifies. float(1<<64)? The same thing plus or minus one? Derive the argument to make it clear.

Honestly, I think I just multiplied `math.MaxInt` by `2` and added `0.5`, so thank you for bringing that up, it should be derived.

> Is the second argument intentionally a float? It may compare equal to the int returned by ceil, but it would be better to use an expression that is actually an int.

Great point, and will do :)

**Review by adonovan — APPROVED** [review]
Looks good! Thanks again.
