### PR TITLE
starlark: add examples of UnpackArgs

### LINKED ISSUE #111: doc: show examples of UnpackArgs
Example: all arguments must be named:

```
if len(args) > 0 {
    return nil, fmt.Errorf("%s: unexpected positional arguments")
}
if err := UnpackArgs(b, args, kwargs, ...); err != nil {
    return nil, err
}
```

Example: equivalent to f(x, y=1, *, z=2):
```
if len(args) > 2 {
    return nil, fmt.Errorf("%s: unexpected positional arguments")
}
var x, y, z int = 0, 1, 2
if err := UnpackArgs(b, args, kwargs, "x", &x, "y?", &y, "z", &z); err != nil {
    return nil, err
}
```

### PR DESCRIPTION
**Pull request by alandonovan**
Fixes #111

### CODE REVIEW

File: starlark/unpack.go [hunk 1]
```diff
@@ -34,10 +34,54 @@ type Unpacker interface {
...
+//      // 1. mixed parameters, like def f(a, b=42, c=None).
+//      err := UnpackArgs("f", args, kwargs, "a", &a, "b?", &b, "c?", &c)
+//
+//      // 2. keyword parameters only, like def f(*, a, b, c=None).
+//      if len(args) > 0 {
+//              return fmt.Errorf("f: unexpected positional arguments")
+//      }
+//      err := UnpackArgs("f", args, kwargs, "a", &a, "b?", &b, "c?")
+//
+//      // 3. positional parameters only, like def f(a, b=42, c=None, /) in Python 3.8.
```
Comment (jayconrod) [inline starlark/unpack.go:54]: The `/` after `c=None` is new to me. Is that new in Python 3? Is it supported here?

Comment (alandonovan) [reply starlark/unpack.go:54]: It's PEP570, new in Python 3.8. (Slash is the opposite of star, geddit?) The parameters are (a, ... /, b, ... *, c, ...), where the a's are positional-only, the b's are positional-or-keyword, and the c's are keyword only. The slash is omitted if there are no a's.

It's not a bad feature as it's symmetric and it helps to reduce inadvertent exposure of parameter names, but I'm not sure Python's function calling convention really needs more stuff. Starlark doesn't currently support it.

**Comment by alandonovan** [comment]
I did initially express them as runnable examples, but I wasn't very happy with the amount of additional code surrounding the one line of interest, especially as I added three or four examples.
