### PR TITLE
starlark: capture free variables by reference

### LINKED ISSUE #170: starlark: dynamic error executing definition of a recursive nested def
Declaring a recursive nested function causes a dynamic error as execution of the def statement, while attempting to build its closure, attempts to load the value of the not-yet-defined local variable that will contain the function.

```
$ cat a.star
def a():
    def b():
        print(b)

print(a())
$ go run ./cmd/starlark/ -nesteddef a.star
Traceback (most recent call last):
  a.star:5: in <toplevel>
  a.star:2: in a
Error: local variable b referenced before assignment
```
How did I not notice this already? It's the classic 'letrec' problem. It's as if I never went to graduate school. :(

Recursion is not essential; the problem arises any time the outer local changes after the closure is created:
```
$ cat d.star 
def a():
    x = 1
    def b(): print(x)
    b()
    x = 2
    b()

a()

$ starlark -nesteddef d.star 
1
1
$ python  d.star 
1
2
```

The solution is, during resolution, to mark local variables such as x that are shared by more than one function (a and b), as "cell" variables, and allocate each one separately at function start. Parameters that are so marked must be spilled into cells in the function prologue. Cells must be accesses and updated using a different indirect opcode to regular locals. A Function's freevars tuple will consist only of references to a subset of its ancestor's cells. That means cells must be first-class Starlark values.

### PR DESCRIPTION
**Pull request by alandonovan**
This change causes closures for nested functions to capture their
enclosing functions' variables by reference. Even though an inner
function cannot update outer variables, it must observe updates to
them made by the outer function.

A special case of this is a nested recursive function f:

   def outer():
       def f(): ...f()...

The def f statement constructs a closure which captures f, and then
binds the closure value to f. If the closure captures by value (as
before this change), the def statement will fail because f is
undefined (see issue #170). Now, the closure captures a reference
to f, so it is safe to execute before f has been assigned.

This is implemented as follows. During resolving, captured local
variables such as f are marked as as "cells". The compiler assumes and
guarantees that such locals are values of a special internal type
called 'cell', and it emits explicit instructions to load from and
store into the cell. At runtime, cells are created on entry to the function;
parameters may be "spilled" into cells as needed.
Each cell variable gets its own allocation to avoid spurious liveness.
A function's tuple of free variables contains only cells.

Fixes #170

### CODE REVIEW

File: starlark/interp.go [hunk 1]
```diff
@@ -52,6 +52,12 @@ func (fn *Function) CallInternal(thread *Thread, args Tuple, kwargs []Tuple) (Va
 		defer fmt.Println("Leaving ", f.Name)
 	}
 
+	// Spill indicated locals to cells.
+	// Each cell is a separate alloc to avoid spurious liveness.
```
Comment (jayconrod) [inline starlark/interp.go]: Thanks for keeping these separate. I've seen a couple bad memory leaks in V8 that were the consequence of allocating an array for captured variables instead of individual cells.
